### PR TITLE
 Modified BPS fan pcb schematic to support 12 fans instead of 4.

### PR DESCRIPTION
**Pull request by tasniabari**
# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

### Minimum Prerequisites
- [X] Pushed changes to branch.
- [x] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable.
- [x] All traces are routed.
- [x] Units are in metric.

### 2D Spacing
- [ ] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [ ] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [ ] The components are aligned with each other when possible.
- [ ] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [ ] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [ ] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [ ] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [ ] Custom footprints have been double checked with the datasheet.
- [ ] Pin 1 of the footprint is labeled in some way.

### Copper Layer
- [ ] The trace widths and trace clearances are greater than JLCPCB's minimum requirements.
- [ ] The trace lengths are as short as possible.
    - Can there be a more optimal route if you go to another layer?
- [ ] Each trace's width is capable of handling the expected current flow.
    - Use PCB width calculator to calculate trace width.
- [ ] *No sharp corners. No trace angles equal to or less than 90 degrees.
- [ ] Traces are in parallel with each other when possible.
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other.
- [ ] There are no random trace appendages.
- [ ] Vias placed in copper pads are fully encompassed in the copper pads.
- [ ] Through-hole components do not have extraneous vias.

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [ ] Visible text sizes are greater than JLCPCB's minimum requirements.
- [ ] All visible text is on the silkscreen layer.
- [ ] All reference labels of each component are not overlapping a copper pad or another component.
- [ ] All connector pins are labeled with a meaningful and helpful name.
- [ ] All LEDs are labeled with a meaningful and helpful name.

### Edge Cut Layer
- [ ] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [ ] The physical outline of the board is on the edge cut layer.
- [ ] Edge cuts are straight and parallel with opposite edge of the board.
- [ ] Mounting holes are aligned.
- [ ] Corners are curved and contoured to mounting holes.

### IMPORTANT NOTICE
- [ ] I am confident that this board will be safe to use in a safety critical environment.
- [ ] I had fun :)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by manthanand** [comment]
image
You added all these labels, but some of them are shorted to others meaning one of them isn't useful. Also, all labels should have wire underneath them so they look pretty. Also what do those labels mean? What do they connect to? Draw a current path for these fans if they were turned on. Would it actually power the fans?

**Comment by manthanand** [comment]
image
Orient this the right way.

**Comment by manthanand** [comment]
All of the CONNECT labels should be the same. Also, it is good practice to not have wires crossing over words.

**Comment by manthanand** [comment]
rename this branch to a version name

**Comment by manthanand** [comment]
You don't need the connect labels. You could just tie everything to GNDPWR. It is easier to understand. Also add a datasheet for the status LED. I think a 45k resistor for that might be too large but depends on what LED we use.

**Comment by HannahSLee14** [comment]
Overall, it's looking good! A few comments:

1. Are these also supposed to be connected to +12 V? Right now, I don't think anything is powering them.
image
2. This is nit-picky but GNDPWR should be pointing downwards and +12V should be pointing upwards
image
3. Do we want to add more protection circuitry for the +12V and GNDPWR? Possibly at least a TVS diode?

Great work so far!

**Comment by pramukap** [comment]
image
image

The schematic is really clean and well organized! I think there's some issues with the layout though, that might stem from the schematic.

I'm wondering if the various +12V and the GNDPWR in the schematic are connected to each other. It doesn't seem like power and ground are hooked up to the rest of the circuit properly

**Comment by pramukap** [comment]
image
I don't know if this is okay or not. The trace runs directly under the all the pads for the mosfet

**Comment by pramukap** [comment]
image
One last note: what does the PWR_FLAG do? I think this could be shorting power and ground.

**Review by pramukap — APPROVED** [review]
The schematic looks good! Well-organized and readable. My only question is, what is the difference btwn the PWR_FLAG and +12V?

**Comment by Champers5000** [comment]
image

Why not just use a single mosfet for all 3 fans? The mosfets are all driven by the same signal, so using 3 mosfets separately seems like a waste of mosfets. The mosfets you chose should be able to handle driving 3 fans

**Review by Champers5000 — COMMENTED** [review]
Fan headers are shorted in the schematic lmao

**Review by Champers5000 — APPROVED** [review]
nice

**Review by pramukap — COMMENTED** [review]
image

Should this PWR_FLAG be shorted to GNDPWR? Also the schematic would look nicer if the circuits were neatly organized. Otherwise looks good!

**Comment by pramukap** [comment]
Overall looks really good! The layout is really clean and easy to follow. Looks easy to solder as well. There are some small things I noticed that I've listed below:

image
I'm getting some DRC errors. I think the dimensions need to be moved from the `f.cu` layer to the `user drawings` layer, or something along those lines

image
I think the `LDRBRDConn` silkscreen print would look better if it was oriented the same as the other silkscreen prints for that connector

I believe the mounting holes need dimensions
Are the ground traces the correct thickness?
Do we need any testpoints for debug purposes on this board?
Will the LED be visible once the board is mounted in the car?

**Review by pramukap — COMMENTED** [review]
Comment above contains my review ^

**Comment by ray4477** [comment]
image

Idk iif im tripping but is there supposed to be a ground plate here? the vias seem floating. Also just a suggestion to make the board smaller is putting components between the connectors on the other side. Im not sure if its that's necessary but if board size is a factor.  My main concern is if there is enough space between the connectors for example J2 and J3. It might be kinda hard to unplug the molex microfits as they got around .3 in between them.


image

**Review by Champers5000 — COMMENTED** [review]
image
These traces are carrying power and could be made thicker. I think you could replace all the traces with 1mm traces

**Review by ray4477 — APPROVED** [review]
looks good

**Comment by manthanand** [comment]
image
We don't like acute angles. Move the resistors to the right so the traces can just go over them.

**Comment by manthanand** [comment]
image
Make GNDPWR traces really thick, have them cover all 3 pads, and use a larger via to connect to the GNDPWR plane.

**Comment by HannahSLee14** [comment]
This board is super neat and organized, so that's really good! A few comments:
- I know on KiCAD, it looks like these are far apart but in reality, they're all less than 1 cm apart. In order to take the Molex connectors out, someone is going to need to be their finger in between two of these connectors. I would keep that in mind when moving things around. You may want to consider staggering them! (see the old BPS Minion shield for an idea about spacing the connectors) 
image

- KiCAD says these aren't connected for me. I think generally, we usually have the trace enter close to the center of the pad. It probably is fine the way it is, considering the trace does go over the pad, but it does make me a little worried 
image

- Make the edge cuts flush with the mounting holes so it's consistent with the other boards
image

- This is me being picky but we can save some space here by moving the mounting holes down
image

- Label what the LED is for - is it a power indicator? We want people to be able to look at the board and tell what it means.
- Did you double-check that the trace size is appropriate for the current we're expecting? 
- You can put your name somewhere! You worked really hard on this board so you earned it

**Pull request merged**
